
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - productreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - productreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - products/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atlas.jpereira.co.uk
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
